package com.springmvc.entity;

public class Buyer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.id_buyer
     *
     * @mbggenerated
     */
    private Integer idBuyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.name_buyer
     *
     * @mbggenerated
     */
    private String nameBuyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.phone_buyer
     *
     * @mbggenerated
     */
    private String phoneBuyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.address_buyer
     *
     * @mbggenerated
     */
    private String addressBuyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.id_buyer
     *
     * @return the value of buyer.id_buyer
     *
     * @mbggenerated
     */
    public Integer getIdBuyer() {
        return idBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.id_buyer
     *
     * @param idBuyer the value for buyer.id_buyer
     *
     * @mbggenerated
     */
    public void setIdBuyer(Integer idBuyer) {
        this.idBuyer = idBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.name_buyer
     *
     * @return the value of buyer.name_buyer
     *
     * @mbggenerated
     */
    public String getNameBuyer() {
        return nameBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.name_buyer
     *
     * @param nameBuyer the value for buyer.name_buyer
     *
     * @mbggenerated
     */
    public void setNameBuyer(String nameBuyer) {
        this.nameBuyer = nameBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.phone_buyer
     *
     * @return the value of buyer.phone_buyer
     *
     * @mbggenerated
     */
    public String getPhoneBuyer() {
        return phoneBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.phone_buyer
     *
     * @param phoneBuyer the value for buyer.phone_buyer
     *
     * @mbggenerated
     */
    public void setPhoneBuyer(String phoneBuyer) {
        this.phoneBuyer = phoneBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.address_buyer
     *
     * @return the value of buyer.address_buyer
     *
     * @mbggenerated
     */
    public String getAddressBuyer() {
        return addressBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.address_buyer
     *
     * @param addressBuyer the value for buyer.address_buyer
     *
     * @mbggenerated
     */
    public void setAddressBuyer(String addressBuyer) {
        this.addressBuyer = addressBuyer;
    }
}