package com.springmvc.entity;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id_pro
     *
     * @mbggenerated
     */
    private Integer idPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name_pro
     *
     * @mbggenerated
     */
    private String namePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price_pro
     *
     * @mbggenerated
     */
    private String pricePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.picture_path_pro
     *
     * @mbggenerated
     */
    private String picturePathPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.describe_pro
     *
     * @mbggenerated
     */
    private String describePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remark_pro
     *
     * @mbggenerated
     */
    private Integer remarkPro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id_pro
     *
     * @return the value of product.id_pro
     *
     * @mbggenerated
     */
    public Integer getIdPro() {
        return idPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id_pro
     *
     * @param idPro the value for product.id_pro
     *
     * @mbggenerated
     */
    public void setIdPro(Integer idPro) {
        this.idPro = idPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name_pro
     *
     * @return the value of product.name_pro
     *
     * @mbggenerated
     */
    public String getNamePro() {
        return namePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name_pro
     *
     * @param namePro the value for product.name_pro
     *
     * @mbggenerated
     */
    public void setNamePro(String namePro) {
        this.namePro = namePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price_pro
     *
     * @return the value of product.price_pro
     *
     * @mbggenerated
     */
    public String getPricePro() {
        return pricePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price_pro
     *
     * @param pricePro the value for product.price_pro
     *
     * @mbggenerated
     */
    public void setPricePro(String pricePro) {
        this.pricePro = pricePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.picture_path_pro
     *
     * @return the value of product.picture_path_pro
     *
     * @mbggenerated
     */
    public String getPicturePathPro() {
        return picturePathPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.picture_path_pro
     *
     * @param picturePathPro the value for product.picture_path_pro
     *
     * @mbggenerated
     */
    public void setPicturePathPro(String picturePathPro) {
        this.picturePathPro = picturePathPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.describe_pro
     *
     * @return the value of product.describe_pro
     *
     * @mbggenerated
     */
    public String getDescribePro() {
        return describePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.describe_pro
     *
     * @param describePro the value for product.describe_pro
     *
     * @mbggenerated
     */
    public void setDescribePro(String describePro) {
        this.describePro = describePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remark_pro
     *
     * @return the value of product.remark_pro
     *
     * @mbggenerated
     */
    public Integer getRemarkPro() {
        return remarkPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remark_pro
     *
     * @param remarkPro the value for product.remark_pro
     *
     * @mbggenerated
     */
    public void setRemarkPro(Integer remarkPro) {
        this.remarkPro = remarkPro;
    }
}